services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: nestjs-api
    build:
      context: .
      dockerfile: demo-api/Dockerfile
    depends_on:
        db:
          condition: service_healthy
    ports:
        - 3000:3000
    environment:
        - PORT=3000
        - POSTGRES_DATABASE=postgres
        - POSTGRES_USERNAME=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
    volumes:
        - ./:/app
